import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-primary-fixed-variant": "#2d476f",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#005049",
        "inverse-primary": "#adc7f7",
        "surface-tint": "#455f88",
        background: "#f7f9fb",
        "on-error": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-high": "#e6e8ea",
        secondary: "#006a61",
        "tertiary-container": "#4f2e00",
        "on-tertiary-container": "#c6955e",
        "secondary-fixed-dim": "#6bd8cb",
        "inverse-surface": "#2d3133",
        outline: "#74777f",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#d6e3ff",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#633f0f",
        "secondary-fixed": "#89f5e7",
        "outline-variant": "#c4c6cf",
        "on-secondary-container": "#006f66",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#321b00",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffddba",
        "on-surface-variant": "#43474e",
        "on-tertiary-fixed": "#2b1700",
        "on-surface": "#191c1e",
        surface: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#f2bc82",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#1a365d",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "on-primary-container": "#86a0cd",
        "secondary-container": "#86f2e4",
        primary: "#002045",
        error: "#ba1a1a",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed": "#00201d",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#adc7f7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-yeseva)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
