import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
        },
        "on-primary-fixed-variant": "#2d476f",
        "surface-dim": "#d8dadc",
        "on-secondary-fixed-variant": "#005049",
        "inverse-primary": "#adc7f7",
        "surface-tint": "#455f88",
        "on-error": "#ffffff",
        "surface-container-high": "#e6e8ea",
        "tertiary-container": "#4f2e00",
        "on-tertiary-container": "#c6955e",
        "secondary-fixed-dim": "#6bd8cb",
        "inverse-surface": "#2d3133",
        outline: "#74777f",
        "surface-variant": "#e0e3e5",
        "primary-fixed": "#d6e3ff",
        "surface-bright": "#f7f9fb",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#633f0f",
        "secondary-fixed": "#89f5e7",
        "outline-variant": "#c4c6cf",
        "on-secondary-container": "#006f66",
        "on-primary": "#ffffff",
        "on-tertiary": "#ffffff",
        tertiary: "#321b00",
        "error-container": "#ffdad6",
        "tertiary-fixed": "#ffddba",
        "on-surface-variant": "#43474e",
        "on-tertiary-fixed": "#2b1700",
        "on-surface": "#191c1e",
        surface: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#eceef0",
        "tertiary-fixed-dim": "#f2bc82",
        "inverse-on-surface": "#eff1f3",
        "primary-container": "#1a365d",
        "surface-container-highest": "#e0e3e5",
        "on-background": "#191c1e",
        "on-primary-container": "#86a0cd",
        "secondary-container": "#86f2e4",
        error: "#ba1a1a",
        "on-primary-fixed": "#001b3c",
        "on-secondary-fixed": "#00201d",
        "surface-container-low": "#f2f4f6",
        "primary-fixed-dim": "#adc7f7",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["var(--font-yeseva)", "serif"],
        heading: ["var(--font-yeseva)", "serif"],
        body: ["var(--font-manrope)", "sans-serif"],
        label: ["var(--font-manrope)", "sans-serif"],
      },
    },
  },
  plugins: [],
};

export default config;
